### ISSUE TITLE
how can i download the dataset

### ISSUE THREAD

**Issue by qq3266452048** [ChristophReich1996/Cell-DETR#10]
wanna get the dataset, but the link in readme to ask for the dataset is invalid. 
Hope to access the dataset thanks

**Comment by ChristophReich1996** [comment]
We have a few toy samples publically available at [trapped_yeast_cell_dataset/test](https://github.com/ChristophReich1996/Cell-DETR/tree/master/trapped_yeast_cell_dataset/test).
