### ISSUE TITLE
Enquiry about validate and test methods in ModelWrapper

### ISSUE THREAD

**Issue by charleneolive** [ChristophReich1996/Cell-DETR#11]
Hello,

Thanks for your interesting paper and for sharing the code.

Could I ask for test method in (model_wrapper.py), there is a conversion of the bounding box coordinates format from (xc yc w h)-> (x0 y0 x1 y1) (lines 351- 354) when calculating the test metrics for the bounding boxes but why is it not the case for the validate method (lines 222-224)? 

Thank you!
Charlene

**Comment by ChristophReich1996** [comment]
Hi @charleneolive,

thanks for pointing this out, I guess you are correct, validate should also use the conversion, but let me check this in detail.

Cheers
Christoph
