### ISSUE TITLE
Enquiry about the difference between ohem and non-ohem

### ISSUE THREAD

**Issue by charleneolive** [ChristophReich1996/Cell-DETR#12]
Hello,
I don't understand if not ohem, why do you index with [:prediction.shape[-1]]? Shouldn't it be the reverse where if ohem is True, then the batch size is reduced?

https://github.com/ChristophReich1996/Cell-DETR/blob/a53f66f3f8360996dc0af1b0f6a44a583c011f7b/lossfunction.py?_pjax=%23repo-content-pjax-container#L436

**Comment by ChristophReich1996** [comment]
Hi @charleneolive,

So we tested online hard example mining (OHEM) during some preliminary experiments. For this reason, the loss function implementation is a bit messy, I would suggest simply ignoring the OHEM parts. In the particular line, which caused confusion, `[:prediction.shape[-1]]` ensures that the class weights (`self.class_weights`) match the number of classes in the prediction. Hope that this explanation solves the confusion.

Cheers
Christoph

**Comment by charleneolive** [comment]
Hello Christoph,

Thanks for your quick reply and for your clarification!
