### ISSUE TITLE
Training without segmentation on my own dataset

### ISSUE THREAD

**Issue by brianw0924** [ChristophReich1996/Cell-DETR#14]
Hi, I would like to ask if I can set the weight of segmentation loss and classification loss to 0?

My own dataset don't have segmentation label, and only have 1 class

does it work on your model?

**Comment by ChristophReich1996** [comment]
Hi @brianw0924,

Thanks for your interest. Yes, if you only want Cell-DETR to perform single-class object detection, and no segmentation and classification, you can set the corresponding loss weights to zero. However, to do this hack you need some dummy labels for the segmentation and class of the correct shape.

Cheers
Christoph
