### ISSUE TITLE
ModulatedDeformConvPack not found!

### ISSUE THREAD

**Issue by samKaranth** [ChristophReich1996/Cell-DETR#2]
from modules.modulated_deform_conv import ModulatedDeformConvPack

I wasn't able to import this package. I tried build from [https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch]
and the modules used to build DCN is deprecated.
Please help with this issue and it would be nice if you upload that modules directory along with latest stable build script for DCN.

**Comment by ChristophReich1996** [comment]
Hi, did you used the [PyTorch 1.0.0 branch](https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/tree/pytorch_1.0.0) of the deformable convolution? We tested the DCN on PyTorch >= 1.4.0 and different CUDA version (10.1, 10.2 & 11.1) on Linux with no problems. But if you have still trouble using the DCN you could possibly implement the ModulatedDeformConvPack by yourself, using the [torchvision DCN](https://pytorch.org/vision/stable/_modules/torchvision/ops/deform_conv.html).

**Comment by ChristophReich1996** [comment]
Small supplement DCN v2 is not available in the current stable (0.8.2) torchvision release. Only the original (v1) version is available. So if you want to use torchvision for the DCN v2, please use the master branch of torchvision. But I highly recommend using the implementation by Dazhi Cheng!

**Comment by samKaranth** [comment]
Thank you for the immediate reply. I cloned master branch of deformable convolution and the packages used for building it was outdated, with [PyTorch 1.0.0 branch](https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/tree/pytorch_1.0.0) it worked perfectly. Awesome Repo BTW!
