### ISSUE TITLE
How to prepare data in .pt format!

### ISSUE THREAD

**Issue by mksarker** [ChristophReich1996/Cell-DETR#3]
Hi,
Please help me to prepare the data in .pt format. 
My data is in coco format and I run maskRCNN on it. 
I need to try with your model also.
Can you please support converting the data to .pt format?

Thanks
Mostafa

**Comment by ChristophReich1996** [comment]
Hi Mostafa, first of all, thanks for your interest. So the `.pt` format is the standard PyTorch format for storing tensors ([see](https://pytorch.org/docs/stable/generated/torch.load.html)). I would either suggest writing your own dataset class for the COCO format or converting the data to the same format as the toy examples. Our format is structured in bounding boxes, classes, inputs, and instances. The bounding box tensors have a shape of [n objects, 4 (y1, x1, y2, x2)]. The classes tensors have a shape of [n objects] with the class index starting with 1. The instance tensors are binary maps for each instance with the shape [n objects, height, width]. And the inputs simply include the input images. For more details, I would recommend loading and inspecting the [toy examples](https://github.com/ChristophReich1996/Cell-DETR/tree/master/trapped_yeast_cell_dataset/test) and the [dataset class](https://github.com/ChristophReich1996/Cell-DETR/blob/master/dataset.py).
Cheers Christoph
