### ISSUE TITLE
Adapting model to more labels

### ISSUE THREAD

**Issue by LSnyd** [ChristophReich1996/Cell-DETR#4]
Hi there,
first of all thank you so much for providing the code to your paper and for the clear explanations. 

I want to use the Cell-DETR model for a use-case with more than 20 labels per image. 
I already got everything running, but it seems like that the model only predicts 12 bounding boxes and masks and the predicted boxes are also all located on one side of the image. 

Do you have any idea where that might come from? Is there an additional hardcoded parameter in the architecture that I need to change? 

Best,
Lisa

**Comment by ChristophReich1996** [comment]
Hi, 
so in our particular use case, we have not more than 10 instances present in a specimen image. Thus, we have set the number of object queries to 12. If you want to detect more instances per image you can increase the parameter `number_of_query_positions: int = 12` in [detr.py](https://github.com/ChristophReich1996/Cell-DETR/blob/130cd0c59b96b7986c8bb9ee564e88f47f7d4f25/detr.py).
Be aware that more object queries lead to an increase in computational complexity both in the CNN encoder and the transformer encoder.

Cheers
Christoph

**Comment by LSnyd** [comment]
Perfect! Thank you so much, my model learns much better now 👍
