### ISSUE TITLE
No module named 'modules'

### ISSUE THREAD

**Issue by walynlee** [ChristophReich1996/Cell-DETR#6]
Hello,I found an issue when running:
File "main.py", line 70, in <module>
    from modules.modulated_deform_conv import ModulatedDeformConvPack
ModuleNotFoundError: No module named 'modules'

**Comment by ChristophReich1996** [comment]
Hi, this error only occurs if the deformable convolution is not installed correctly. Please follow the instruction in the [readme](https://github.com/ChristophReich1996/Cell-DETR) (dependencies section) to install the deformable convolution, then Cell-DETR should run fine.

[Related issue](https://github.com/ChristophReich1996/Cell-DETR/issues/2)
