### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_75'

### ISSUE THREAD

**Issue by jjb202** [ChristophReich1996/Cell-DETR#9]
python setup.py build install
something error in this step

------------------------------------
gcc -pthread -B /home/szp/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/szp/anaconda3/include/python3.8 -c /home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cpu/deform_cpu.cpp -o build/temp.linux-x86_64-3.8/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cpu/deform_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=DCN -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/szp/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/szp/anaconda3/include/python3.8 -c /home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cpu/deform_psroi_pooling_cpu.cpp -o build/temp.linux-x86_64-3.8/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cpu/deform_psroi_pooling_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=DCN -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/szp/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/szp/anaconda3/include/python3.8 -c /home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cpu/modulated_deform_cpu.cpp -o build/temp.linux-x86_64-3.8/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cpu/modulated_deform_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=DCN -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/bin/nvcc -DWITH_CUDA -I/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/szp/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/szp/anaconda3/include/python3.8 -c /home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cuda/deform_psroi_pooling_cuda.cu -o build/temp.linux-x86_64-3.8/home/szp/Cell-DETR/Deformable-Convolution-V2-PyTorch/src/cuda/deform_psroi_pooling_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=DCN -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_75'
error: command '/usr/bin/nvcc' failed with exit status 1

**Comment by ChristophReich1996** [comment]
Hey, so I guess you have to update the `nvcc` arguments that they fit your type of GPU and CUDA version.

https://github.com/ChristophReich1996/Cell-DETR/blob/b7b387a18650c5251ec9d25473442b7758780152/pade_activation_unit/cuda/setup.py#L311-L315

Cheers Christoph
